# Activa el perfil "local" para que busque y cargue el archivo application-local.properties

spring.profiles.active=local

# Configuraciones globales no sensibles

server.port=8080

# Forzar a Spring Security a mostrar el flujo de autenticación en la consola
logging.level.org.springframework.security=DEBUG
# Ver el rastro de carga del contexto de JAAS
logging.level.org.springframework.security.authentication.jaas=DEBUG